services:
  n8n:
    build: ./n8n
    container_name: lab2_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - GENERIC_TIMEZONE=Europe/Moscow
    volumes:
      - n8n_data:/home/node/.n8n
      - shared_files:/files
    networks:
      - lab2_network

  autosub:
    build: ./autosub
    container_name: lab2_autosub
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - ASR_MODEL=tiny
      - ASR_ENGINE=openai_whisper
      - ASR_DEVICE=cpu
    volumes:
      - shared_files:/files
    networks:
      - lab2_network

  ollama:
    image: ollama/ollama:latest
    container_name: lab2_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - lab2_network

volumes:
  n8n_data:
  ollama_data:
  shared_files:

networks:
  lab2_network:
    driver: bridge